management:
  endpoints:
    web:
      exposure:
        include: health,beans,metrics,env
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  datasource:
    password: '600099'
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/bank-system
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
mail:
  properties:
    mail:
      smtp:
        auth: 'true'
        starttls:
          enable: 'true'
  password: bcLyFagT9e88xiZ
  port: '587'
  host: smtp.gmail.com
  protocol: smtp
  username: test.banksystem@gmail.com
jwt:
  secret: intexsoft
isEmailSenderActive: 'false'
packagesToScan: by.ganevich.entity
currency-service:
  url: http://localhost:8083/rates/
validTime: '15'
