management:
  endpoints:
    web:
      exposure:
        include: health,beans,metrics,env
  endpoint:
    health:
      show-details: always
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
  jpa:
    show-sql: 'true'
mail:
  properties:
    mail:
      smtp:
        auth: 'true'
        starttls:
          enable: 'true'
  password: bcLyFagT9e88xiZ
  host: smtp.gmail.com
  protocol: smtp
  port: '587'
  username: test.banksystem@gmail.com
db:
  password: '600099'
  dialect: org.hibernate.dialect.PostgreSQLDialect
  url: jdbc:postgresql://localhost:5432/bank-system
  username: postgres
  driver: org.postgresql.Driver
packagesToScan: by.ganevich.entity
jwt:
  secret: intexsoft
isEmailSenderActive: 'false'
currency-service:
  url: http://localhost:8083/rates/
validTime: '15'
