management:
  endpoints:
    web:
      exposure:
        include: health,beans,metrics,env
  endpoint:
    health:
      show-details: always
db:
  password: '600099'
  dialect: org.hibernate.dialect.PostgreSQLDialect
  username: postgres
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bank-system
mail:
  properties:
    mail:
      smtp:
        auth: 'true'
        starttls:
          enable: 'true'
  password: bcLyFagT9e88xiZ
  port: '587'
  host: smtp.gmail.com
  protocol: smtp
  username: test.banksystem@gmail.com
spring:
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
  jpa:
    show-sql: 'true'
jwt:
  secret: intexsoft
isEmailSenderActive: 'false'
packagesToScan: by.ganevich.entity
currency-service:
  url: http://localhost:8083/rates/
validTime: '15'